make watch-admin fails with:  Cannot find module 'webpack-cli/bin/config-yargs'
Can't run make watch-admin in Dockware as it stops with the following error:

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /var/www/html/vendor/shopware/administration/Resources/app/administration/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/www/html/vendor/shopware/administration/Resources/app/administration/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/html/vendor/shopware/administration/Resources/app/administration/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
makefile:65: recipe for target 'watch-admin' failed
make: *** [watch-admin] Error 1

Fixes Error: Cannot find module 'webpack-cli/bin/config-yargs'

If you're using webpack 4 you should use "webpack serve" instead of "webpack-dev-server":
https://stackoverflow.com/questions/64803892/error-error-cannot-find-module-webpack-cli-bin-config-yargs-require-stack
https://github.com/webpack/webpack-dev-server/issues/2424